image: node:lts
cache:
    key: lettercms-client
    paths:
      - node_modules

##### DEFINE STAGES
stages:
  - deploy


########## App Review Jobs
review:
  stage: deploy
  script:
    npx vercel --name lettercms-client --confirm -t $VERCEL_TOKEN

